//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TourDuLich.BUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDungTour
    {
        public int MaDoan { get; set; }
        public string HanhTrinh { get; set; }
        public string KhachSan { get; set; }
        public string DiaDiemThamQuan { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
    }
}
